# Define the list of plot types
PLOT_TYPES = [
    "Histogram", 
    "Line Plot", 
    "Scatter Plot", 
    "ABC Analysis", 
    "Pareto Chart", 
    "Capacity Planning Analysis", 
    "Contract Management Analysis", 
    "Demand Forecasting Analysis", 
    "Risk Assessment and Mitigation", 
    "Cost to Serve Analysis", 
    "Warehouse Layout", 
    "Lead Time Analysis", 
    "Order Fulfillment Analysis",
    "Product Lifecyle Analysis",
    "Quality Control and Inspection Analysis",
    "Service Level Analysis",
    "SKU Rationalization",
    "Supplier Consolidation Analysis",
    "Risk Analysis",
    "SOP Analysis",
    "Customer Segmentation Analysis",
    "Reverse Logistics Analysis",
    "Supplier Performance Analysis",
    "Supply Chain Segmentation Analysis",
    "Iventory Optimization",
    "Production Planning and Scheduling Analysis"
]
